I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 500, in script
    with flash
  File "game/script.rpy", line 500, in <module>
    with flash
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 500, in script
    with flash
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1651, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 500, in <module>
    with flash
NameError: name 'flash' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
HISE DSM 1.0
Mon May 15 23:29:07 2023
